# -*- coding: utf-8 -*-
"""Visualizar imagem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jpQFzOYSi_t_2mkdtLRXZXhEPuoVYg5J

Instalar as bibliotecas GDAL e RASTERIO
"""

!pip install gdal
!pip install rasterio

# IMPORTAR A BIBLIOTECA TIFFFILE
import tifffile as tif

img = tif.imread('/content/drive/MyDrive/GEE/stacked_image_with_indices_2020.tif')

!pip install imagecodecs

img.shape

# IMPORTAR A BIBLIOTECA MATPLOTLIB COM O METODO PYPLOT
import matplotlib.pyplot as plt

plt.imshow(img[:,:,1])

# PLOTAR COM OUTRA ESCALA DE COR
plt.imshow(img[:,:,4], cmap='grey' )

# INSTALAR A BIBLIOTECA SPECTRAL
!pip install spectral

#IMPORTAR O MÉTODO IMSHOW DA BIBLIOTECA SPECTRAL
from spectral import imshow

imshow(img, bands=(4,3,2))

"""GDAL"""

from osgeo import gdal

img2 = gdal.Open('/content/drive/MyDrive/GEE/stacked_image_with_indices_2020.tif')

print(img2)

img3 = img2.ReadAsArray()

img3.shape

imshow(img3, bands=(4,3,2))

imshow(img3[3,:,:])

img3 = img3.swapaxes(0,2)

img3.shape

img3 = img3.swapaxes(0,1)

img3.shape

imshow(img3, bands=(4,3,2))

b2 = img2.GetRasterBand(2).ReadAsArray()

"""RASTERIO"""

import rasterio
from rasterio.plot import show

rst = rasterio.open('/content/drive/MyDrive/GEE/stacked_image_with_indices_2020.tif')

print(rst)

show(rst)

show(rst, cmap='Greys_r')

b1 = rst.read(1)
b2 = rst.read(2)
b4 = rst.read(4)

print("Shape of b1:", b1.shape)
print("Shape of b2:", b2.shape)
print("Shape of b4:", b4.shape)
stack = np.dstack([b2,b1,b4])

import numpy as np

imshow(stack)

# Substituir valores NaN por zero
stack_filled = np.nan_to_num(stack, nan=0)

# Verificar se ainda existem NaNs (deve retornar False)
print("Existem NaNs após preencher?", np.isnan(stack_filled).any())

imshow(stack_filled)